### ISSUE TITLE
uJoystick: add offset feature

### ISSUE THREAD

**Issue by SimonRohou** [ENSTABretagneRobotics/moos-ivp-toutatis#151]
(configurable in .moos files)

**Comment by schvarcz** [comment]
I think that the goal here is to define the normal value when the joystick is the "dead" position.

If so, it already exist. You can define a MAX and MIN value for an axis in the uJoystick configuration file. The middle point between them, considering the SCALE_RATIO, will be set as the value in the "dead" position.

This information was not in the .moos example before, but it is now in the pull request https://github.com/ENSTABretagneRobotics/moos-ivp-enstabretagne/pull/153.

**Comment by SimonRohou** [comment]
Thanks!
