### ISSUE TITLE
TODO: Link the thrusters values to Pololu

### ISSUE THREAD

**Issue by muriloksantos** [ENSTABretagneRobotics/moos-ivp-toutatis#24]
In the iSaucisse app, the calculated values of thrusters (U1_SIDE_THRUSTER_ONE, U2_SIDE_THRUSTER_TWO, U3_VERTICAL_THRUSTER) must be linked to the Pololu variables to turn the thrusters phisically.

**Comment by SimonRohou** [comment]
Done.
