### ISSUE TITLE
To Be checked : 

### ISSUE THREAD

**Issue by ThomasLeMezo** [ENSTABretagneRobotics/moos-ivp-toutatis#43]
- [x] Network (Day1)
  Needed: antennas, computers
- [x] INS Calibration (Day1)
  Needed: Tree, Wifi router
- [x] Take the origin of the frame precisely with the GPS (Day1)
- [x] Depth regulation (Day1)
- [x] Heading regulation (Day1)
- [ ] Boat
  - [ ] Waypoint Navigation (Ardupilot, Maxime)
  - [ ] Observation equations for the state observers (Day1) (Jeremy)
  - [ ] Integration GPS/Modem code
- [x] Take different sonar images, at different angles (Day1)
- [x] Magnetic declination 
- [x] + XSens Lat, Long Set-up
- [x] Check the rules
- [x] Estimate the damping and Coeff matrix
- [x] See what the weird columns are on the border of the water
- [ ] Safety buoy
- [x] OpenCV (Simon)

**Comment by ClementAubry** [comment]
early coding?
