### ISSUE TITLE
Doc XML

### ISSUE THREAD

**Issue by ThomasLeMezo** [ENSTABretagneRobotics/moos-ivp-toutatis#5]
Serait-il possible d'ajouter dans la doc la description des paramètres du fichier de configuration ".moos" ?

**Comment by SimonRohou** [comment]
Le fichier .moos dans chaque répertoire source est la doc d'utilisation. Le commenter au maximum.
Pour un exemple de doc : 
`pNomApp -e`

Sinon, voir directement la doc version html.
