### ISSUE TITLE
Navigator App

### ISSUE THREAD

**Issue by ClementAubry** [ENSTABretagneRobotics/moos-ivp-toutatis#75]
The aim is to have an App that give all necessary information to the AUV driver when in ROV mode.

REQUIREMENT : 
- Need to be as simple as possible
- No dependencies from libs that are not already installed

FEATURES : 
- INS data (MTI XSens + Razor) [IMU_*]
- Immersion [DEPTH]
- Bathymetry [ECHOSOUNDER_RANGE]
- GPS data with Reliability criterion from @nicolaje (See Issue#66)
- Sonar parameters
- X, Y positionning

**Comment by nicolaje** [comment]
FLTK is the library used to make IVP's GUI apps, so it is already installed. Might be useful to check if it is interesting.

**Comment by SimonRohou** [comment]
For now, I propose a simple AppCasting MOOSApp with a build report containing all necessary information.

**Comment by SimonRohou** [comment]
See uNavScreen.
